# Generated by Django 4.0.3 on 2022-03-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('ave_rate', models.IntegerField(default=0, verbose_name='avrage rate')),
                ('rate_amount', models.IntegerField(default=0)),
                ('total_rate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('ave_rate1', models.IntegerField(default=0)),
                ('total_rate1', models.IntegerField(default=0)),
                ('rate_amount1', models.IntegerField(default=0)),
                ('ave_rate2', models.IntegerField(default=0)),
                ('total_rate2', models.IntegerField(default=0)),
                ('rate_amount2', models.IntegerField(default=0)),
                ('ave_rate3', models.IntegerField(default=0)),
                ('total_rate3', models.IntegerField(default=0)),
                ('rate_amount3', models.IntegerField(default=0)),
                ('ave_rate4', models.IntegerField(default=0)),
                ('total_rate4', models.IntegerField(default=0)),
                ('rate_amount4', models.IntegerField(default=0)),
                ('Professor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PROFESSOR_2', to='rate.professor')),
                ('Professor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PROFESSOR_3', to='rate.professor')),
                ('Professor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PROFESSOR_4', to='rate.professor')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate.module')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate.professor')),
            ],
        ),
    ]
