# Generated by Django 4.0.3 on 2022-03-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_alter_moduleinstance_professor2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinstance',
            name='Professor3',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='Professor4',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='ave_rate3',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='ave_rate4',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='rate_amount3',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='rate_amount4',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='total_rate3',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='total_rate4',
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='Professor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PROFESSOR_2', to='rate.professor'),
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate.professor'),
        ),
    ]
